### ISSUE TITLE
Cis 1.3

### ISSUE THREAD

**Issue by tammyandlee** [ComplianceAsCode/compliance-operator#272]
Is the cis profile going to be updated to version 1.3 (12-12-2022)? 

Thanks in advance,
Lee

**Comment by jhrozek** [comment]
> Is the cis profile going to be updated to version 1.3 (12-12-2022)?
> 
> Thanks in advance, Lee

(the cis profile is not implemented by the operator, but the https://github.com/ComplianceAsCode/content repo)

yes, although probably 1.4. There's been changes in ocp cis profile 1.3 that are incompatible with how OCP works and we need to work with CIS on fixing them.
