### ISSUE TITLE
Remediation and baseline

### ISSUE THREAD

**Issue by bortek** [ComplianceAsCode/compliance-operator#37]
Hi

I have run the scan using ocp4-cis profile and have the following questions.

- What is suggested in the remediations, why isn't it is already "applied" to the cluster right from the beginning it's installation?
- Has the remediations been tested on the openshift cluster and showed that they do not actually break the control plane or other components? There are various changes like changes to the ciphers, iptables, etc. Some of them simple ones but others can have quite severe consequences.
- Is the cluster still supported if remediations have been applied?

**Comment by jhrozek** [comment]
> Hi
> 
> I have run the scan using ocp4-cis profile and have the following questions.
> 
>     * What is suggested in the remediations, why isn't it is already "applied" to the cluster right from the beginning it's installation?
> 

So there's two ways of answering this:
 - why don't we ship some compliant images or a way to install a compliant cluster. The short answer is that it's not been implemented, but it's on our roadmap. Some changes (like https://fedoraproject.org/wiki/Changes/OstreeNativeContainer) have not been available before, others are a question of priorities and time
 - why are the remediations not the default already - some can be and if you think you've identified some that should be the default, raise them. We try to file issues across OCP for things where the default should be changed, but there's always some concern about backwards compatibility. More importantly, OCP defaults support a very broad range of use-cases and some remediations can affect the functionality of the cluster in various ways, be it performance, interoperability etc..
 
 
>     * Has the remediations been tested on the openshift cluster and showed that they do not actually break the control plane or other components? There are various changes like changes to the ciphers, iptables, etc. Some of them simple ones but others 
can have quite severe consequences.

It depends. We don't test all OCP components with all combinations of remediations, but the basics do work. You can check our e2e test suite, it's all open source (https://github.com/ComplianceAsCode/ocp4e2e/)

> 
>     * Is the cluster still supported if remediations have been applied?

Yes. I guess there might be a fine line where you could set a very nonsensical variables where you might affect the functionality of the cluster, but in the end, the remediations don't do anything you can't do yourself by applying MCs/kubeletConfig/etc..

**Comment by bortek** [comment]
Thanks for your reply. I have a certain amount of remedations that needs to be applied according to the scan. My strategy would now be to split them into 3-4 groups and will then apply one by one (pausing mcp in advance). Let's if the cluster will tolerate it.
