### ISSUE TITLE
Different node Labels and Roles

### ISSUE THREAD

**Issue by bortek** [ComplianceAsCode/compliance-operator#42]
Hi

Lets say my compute nodes have different labels and roles than worker and therefore machineconfigpool called worker have 0 nodes in it while another mcp has those "worker" nodes. Or even more I have more worker nodes with roles infra. How do I set a scan setting so that it scans those nodes too? 

There is this roles option in the scansetting object

schedule: 15 01 19 * *
roles:
  - worker
  - master  

But are the actual scans designated to master nodes and worker nodes different from each other or they are all the same? What I mean is that is if I just add more roles to the list of roles in the scansetting object is that all I need to do ?

**Comment by bortek** [comment]
Tanks for the explanation but I do still need a clarification on this: How would I go about if I wanted to add scans for set of nodesl labeled "infra" or "customlabel1" ? Is it enough to just add role name to scansetting object or do I need to do something else?

**Comment by JAORMX** [comment]
@bortek you need to add the roles in the ScanSetting object. You just need to make sure that the labels are in an appropriate format which is `node-role.kubernetes.io/<role name>`

**Comment by bortek** [comment]
Great! thanks for clarification.
