### ISSUE TITLE
To add multi-arch support for compliacen-operator images

### ISSUE THREAD

**Issue by gauravpbankar** [ComplianceAsCode/compliance-operator#79]
As part of the security work for OCP, we need Compliance operator to be get supported for Power, for that we are planning to have all images as Multi-arch supported.

As per our understanding there are Four images which required for deployment of compliance-operator and also they should be multi-arch supported,
Below is list for the same.

- Compliance-operator
- Compliance-operator-index 
- openscap-ocp
- Compliance-operator-bundle

We are already worked on Compliance-operator, openscap-ocp images using Github action and those are multi-arch supported, and we have tested them.

For getting multi-arch support for compliance-operator, openscap-ocp images can we raise PR as we have tested them.

Note: For Compliance-operator-index image which is depending on Compliance-operator-bundle, as Compliance-operator-index is not having any docker file. So how would you suggest to have multi-arch support?

**Comment by jhrozek** [comment]
> For getting multi-arch support for compliance-operator, openscap-ocp images can we raise PR as we have tested them.

Sure, go ahead.

> Note: For Compliance-operator-index image which is depending on Compliance-operator-bundle, as Compliance-operator-index > is not having any docker file. So how would you suggest to have multi-arch support?

For testing (see the `index-image:` target and the `opm:` target in the Makefile) we build an index using `opm`. Looking at https://github.com/operator-framework/operator-registry/releases it looks like `opm` supports also ppc64le and s390x, would that help?

You should maybe note PR #41 that will restructure the Makefile quite a bit. I'm not sure how much your PR would depend on Makefile, but if it does a lot, you might want to check the new targets there.

**Comment by gauravpbankar** [comment]
As per discussed we have raised PR for compliance operator and content images below are the link for the same:

PR link for compliance-opeartor repo:
https://github.com/ComplianceAsCode/compliance-operator/pull/80

PR link for content repo:
https://github.com/ComplianceAsCode/content/pull/9330

**Comment by gauravpbankar** [comment]
As part of the security work for OCP, we need Compliance operator to be get supported for Power, for that we are planning to have all images as Multi-arch supported.



As per our understanding there are Four images which required for deployment of compliance-operator and also they should be multi-arch supported,
Below is list for the same.



- Compliance-operator
- Compliance-operator-index
- openscap-ocp
- Compliance-operator-bundle



We are already working on Compliance-operator, openscap-ocp and content images using Github action and those are multi-arch supported, and we have tested them.
PR links for above images:
Compliance-operator : https://github.com/ComplianceAsCode/compliance-operator/pull/83
openscap-ocp: https://github.com/ComplianceAsCode/compliance-operator/pull/83
content: https://github.com/ComplianceAsCode/content/pull/9330



For Compliance-operator-index image as we do not have dockerfile which can be required for github action to give multi-arch support for compliance-operator-index image.



We are having below Approach:
1. We need to update clusterserviceversion yaml files with updated multi-arch images (because Currently the images present in clusterserviceversion yaml files are not multi-arch and has only amd64 support)
2. After updating csv files we need to build bundle image.
3. Using newly built bundle image, we can create index.Dockerfile by providing --generate option to opm index command in Makefile.
4. After generating the index.Dockerfile which can be used to build index image, we can then build multi-arch index image using github action.



Example for building index image in github action:

```
- name: Build index image for ppc64le
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}-linux-ppc64le
          arch: ppc64le
          containerfiles: |
            ./index.Dockerfile

```


We have already tested this and it is working fine.  

Please let us know can we raise PR for index image as per above approach?

**Comment by aditijadhav38** [comment]
Hi Team,

As per drafted in below image, currently the images are pushed to different repositories.
1. For installing and testing CO through CLI, images are pushed to [Quay.io](http://quay.io/](https://quay.io/repository/compliance-operator/compliance-operator?tab=info))
2. For installing and testing CO through web console, images are pushed to [RedHat registry](https://catalog.redhat.com/software/containers/compliance/openshift-compliance-rhel8-operator/607dc35087c834779d776118).
3. For internal testing, images are pushed to [ghcr.io](http://ghcr.io/) 

Hence could you please confirm the location where we need to push/pull images for compliance operator?

![OCP Security and Compliance](https://user-images.githubusercontent.com/25427151/185938479-5728644c-86ac-4635-8de5-8cb30d7201a5.png)

**Comment by jhrozek** [comment]
> Hi Team,
> 
> As per drafted in below image, currently the images are pushed to different repositories.
> 
>     1. For installing and testing CO through CLI, images are pushed to [Quay.io](http://quay.io/%5D(https://quay.io/repository/compliance-operator/compliance-operator?tab=info))
> 

Upstream releases are pushed to quay.

>     2. For installing and testing CO through web console, images are pushed to [RedHat registry](https://catalog.redhat.com/software/containers/compliance/openshift-compliance-rhel8-operator/607dc35087c834779d776118).

This is not entirely correct, the RH registry is what is built internally in RH's buildsystem. The installation method is not as relevant as using different base images and the whole pipeline that includes security scanning etc. These are also the only images that are supported, documented and go through QE.

> 
>     3. For internal testing, images are pushed to [ghcr.io](http://ghcr.io/)
> 

IIRC, ghcr is what's used for images built after every pull request with GH actions.
> 
> Hence could you please confirm the location where we need to push/pull images for compliance operator?
> 
> ![OCP Security and Compliance](https://user-images.githubusercontent.com/25427151/185938479-5728644c-86ac-4635-8de5-8cb30d7201a5.png)

**Comment by mrogers950** [comment]
> Hi Team,
> 
> We are adding approach for multi-arch index support using github action:
> 
> We are already working on Compliance-operator, openscap-ocp and content images using Github action and those are multi-arch supported, and we have tested them. PR links for above images: Compliance-operator : #83 openscap-ocp: #83 content: [ComplianceAsCode/content#9330](https://github.com/ComplianceAsCode/content/pull/9330)
> 
> For Compliance-operator-index image as we do not have dockerfile which can be required for github action to give multi-arch support for compliance-operator-index image.
> 
> We are having below Approach:
> 
> 1. We need to update clusterserviceversion yaml files with updated multi-arch images (because Currently the images present in clusterserviceversion yaml files are not multi-arch and has only amd64 support)
> 2. After updating csv files we need to build bundle image.
> 3. Using newly built bundle image, we can create index.Dockerfile by providing --generate option to opm index command in Makefile.
> 4. After generating the index.Dockerfile which can be used to build index image, we can then build multi-arch index image using github action.
> 
> Example for building index image in github action:
> 
> ```
> - name: Build index image for ppc64le

Just to clarify, you should not need to build an index for each architecture, instead you would build one index that points to your bundle, and that bundle contains the manifest list reference that was pushed as part of the build actions.


>         uses: redhat-actions/buildah-build@v2
>         with:
>           image: ${{ env.IMAGE_NAME }}
>           tags: ${{ env.IMAGE_TAG }}-linux-ppc64le
>           arch: ppc64le
>           containerfiles: |
>             ./index.Dockerfile
> ```
> 
> We have already tested this and it is working fine.
> 
> Please let us know can we raise PR for index image as per above approach?

Note that we are currently finishing a big overhaul of the Makefile in #41 . Part of the changes will be making it easier to create a bundle and index for specific images, so I would suggest waiting until that PR is committed.

**Comment by mrogers950** [comment]
> Hi Team,
> 
> As per drafted in below image, currently the images are pushed to different repositories.
> 
> 1. For installing and testing CO through CLI, images are pushed to [Quay.io](http://quay.io/%5D(https://quay.io/repository/compliance-operator/compliance-operator?tab=info))
> 2. For installing and testing CO through web console, images are pushed to [RedHat registry](https://catalog.redhat.com/software/containers/compliance/openshift-compliance-rhel8-operator/607dc35087c834779d776118).
> 3. For internal testing, images are pushed to [ghcr.io](http://ghcr.io/)
> 
> Hence could you please confirm the location where we need to push/pull images for compliance operator?
> 
> ![OCP Security and Compliance](https://user-images.githubusercontent.com/25427151/185938479-5728644c-86ac-4635-8de5-8cb30d7201a5.png)

>  `It is not multi-arch, it provides independent images for each arch.`:

This is part of multi-arch. independent architecture builds are produced and included in a manifest list (this is what the proposed github actions do). Images are pulled by the manifest list SHA and that resolves the platform specific architecture.

> `Deploying works from Web Console`

Note that when you deploy from the web console on an OCP install, it's pulling the architecture-relevant images that RH has published in the container catalog (we usually refer to these as downstream)

> `From CLI is does not work.`

CLI install currently only references the quay.io images (these are more or less "convenience" images that a developer builds locally when creating a new version release). In PR #41 we have better support for deploying custom images from the source tree. 

>  `Weird Situation: Multiple Image Repositories`

Like Jakub mentioned, this really comes down to what we can say about the support for each repo. Simply put:
- Upstream quay.io images: convenience, operator testing (providing a working default deployment),
- Downstream RH catalog: Supported by RH, QE tested, signed, etc.
- gchr.io: For GH workflow auto-builds, since it includes signing.

**Comment by aditijadhav38** [comment]
Hi @jhrozek @mrogers950 Thanks for providing brief overview of image release process.
However could you please let us know how the image releasing process will work for the merged PR #83 
Also please confirm if the images will be pushed to Quay.io for the new release and when should we expect that?

**Comment by jhrozek** [comment]
> Hi @jhrozek @mrogers950 Thanks for providing brief overview of image release process. However could you please let us know how the image releasing process will work for the merged PR #83 

Since the GH action should be triggered on pushing to the master branch (or the v* branches for the releases) we should know how they work when other commits are merged, currently that PR is the latest in the tree.

> Also please confirm if the images will be pushed to Quay.io for the new release and when should we expect that?

I don't see anything in the GH action that would push to quay.

More generally -- can you explain why it matters? What is the intended use of the multiarch container images?

It can't be production use because these images don't go through QE, only the in-house built images that are released through the RH container reqistry are. Why is ghcr not suitable for testing and development?

**Comment by gauravpbankar** [comment]
@jhrozek :

 Thanks for the response.
    Actually our main concern was related to installing compliance operator through CLI.
    Because as per our understanding, when we install compliance-operator through web console it uses images from RH registry which has support all arch including ppc64le,amd64 and s390x.
    But when we try to install compliance operator through CLI, it pulls images from Quay.io registry which does not have xupport for ppc64le.
    Following is the file which pulls images from Quay.io
    https://github.com/ComplianceAsCode/compliance-operator/blob/master/deploy/operator.yaml
    But when we raise PR the images are getting pushed to ghcr.io, thus the confusion happened.
    Hence could you please let us know what we are supposed to do in case we need Quay.io images multi-arch in order to install CO through CLI.

**Comment by jhrozek** [comment]
> @jhrozek :
> 
> Thanks for the response. Actually our main concern was related to installing compliance operator through CLI. Because as per our understanding, when we install compliance-operator through web console it uses images from RH registry which has support all arch including ppc64le,amd64 and s390x. But when we try to install compliance operator through CLI, it pulls images from Quay.io registry which does not have xupport for ppc64le. Following is the file which pulls images from Quay.io https://github.com/ComplianceAsCode/compliance-operator/blob/master/deploy/operator.yaml But when we raise PR the images are getting pushed to ghcr.io, thus the confusion happened. Hence could you please let us know what we are supposed to do in case we need Quay.io images multi-arch in order to install CO through CLI.

This is not the right way to install the official bits via CLI. This deploys the upstream bits, not through the OLM but by creating a Deployment directly, so you don't get upgrades etc. This method is really only useful for testing or anyone running a "community version". But not supported or endorsed by RH.

I thought we cleared up the confusion [earlier in this ticket](https://github.com/ComplianceAsCode/compliance-operator/issues/79#issuecomment-1223888881).

We have the procedure to install CO through the CLI documented in the [RH docs](https://docs.openshift.com/container-platform/4.11/security/compliance_operator/compliance-operator-installation.html#installing-compliance-operator-cli_compliance-operator-installation). I haven't tested it on non-Intel, but I would hope it works.

HTH

**Comment by aditijadhav38** [comment]
Hi @jhrozek 
We have tested CO installation using [RH docs](https://docs.openshift.com/container-platform/4.11/security/compliance_operator/compliance-operator-installation.html#installing-compliance-operator-cli_compliance-operator-installation), and it is working fine on ppc64le.

**Comment by jhrozek** [comment]
On Fri, Aug 26, 2022 at 04:53:19AM -0700, Jakub Hrozek wrote:
> > @jhrozek :
> > 
> > Thanks for the response. Actually our main concern was related to installing compliance operator through CLI. Because as per our understanding, when we install compliance-operator through web console it uses images from RH registry which has support all arch including ppc64le,amd64 and s390x. But when we try to install compliance operator through CLI, it pulls images from Quay.io registry which does not have xupport for ppc64le. Following is the file which pulls images from Quay.io https://github.com/ComplianceAsCode/compliance-operator/blob/master/deploy/operator.yaml But when we raise PR the images are getting pushed to ghcr.io, thus the confusion happened. Hence could you please let us know what we are supposed to do in case we need Quay.io images multi-arch in order to install CO through CLI.
> 
> This is not the right way to install the official bits via CLI. This deploys the upstream bits, not through the OLM but by creating a Deployment directly, so you don't get upgrades etc. This method is really only useful for testing or anyone running a "community version". But not supported or endorsed by RH.
> 
> I thought we cleared up the confusion [earlier in this ticket](https://github.com/ComplianceAsCode/compliance-operator/issues/79#issuecomment-1223888881).
> 
> We have the procedure to install CO through the CLI documented in the [RH docs](https://docs.openshift.com/container-platform/4.11/security/compliance_operator/compliance-operator-installation.html#installing-compliance-operator-cli_compliance-operator-installation). I haven't tested it on non-Intel, but I would hope it works.

Thank you for the confirmation!

Please let us know if the GH actions for the multi-arch images are still needed.

**Comment by mrogers950** [comment]
@aditijadhav38 @gauravpbankar FYI the Z build has come up with a failure in our latest release PR: https://github.com/ComplianceAsCode/compliance-operator/pull/125 
We're not going to hold the PR for this failure, so it can be addressed in a separate PR afterwards. 

From the latest discussion here it sounds like the downstream images satisfy your needs. Should we disable these jobs if you're not using the images built by them?

**Comment by gauravpbankar** [comment]
Hi @mrogers950 ,

Yes. As our downstream images are working with power as expected so we can disable this this jobs as we are getting issue with Z images.

**Comment by prb112** [comment]
Spoke to @mrogers950 about issue, and we agreed to remove the Jobs and rely on downstream to build the multiarch images.  @gauravpbankar please confirm

**Comment by prb112** [comment]
Dug into the issue 

```
[Fail] Resultserver testing Raw result directory rotation [It] Rotates directories according to the rotation policy (3 directories with one lost+found and policy=2) 
/go/src/github.com/openshift/compliance-operator/cmd/manager/resultserver_test.go:160
```

There is an implied wait when creating the directory and files in BeforeEach test using `time.Sleep(100 * time.Millisecond)`. 

When I added some logging to the test, I found: 

```
2022/10/25 17:08:28 Directory /tmp/rotate-root4097677180/rotate-13713656550 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:28 Directory /tmp/rotate-root4097677180/rotate-22092874256 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:28 Directory /tmp/rotate-root4097677180/rotate-31859717235 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:28 Post-Sorted
2022/10/25 17:08:28 Directory /tmp/rotate-root4097677180/rotate-13713656550 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:28 Directory /tmp/rotate-root4097677180/rotate-22092874256 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:28 Directory /tmp/rotate-root4097677180/rotate-31859717235 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:29 Pre-Sorted
2022/10/25 17:08:29 Directory /tmp/rotate-root1711445415/rotate-12070323603 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:29 Directory /tmp/rotate-root1711445415/rotate-24065574402 2022-10-25 17:08:28 +0000 UTC
2022/10/25 17:08:29 Directory /tmp/rotate-root1711445415/rotate-31947875413 2022-10-25 17:08:28 +0000 UTC
```

[time.go](https://cs.opensource.google/go/go/+/refs/tags/go1.18.2:src/time/time.go) doesn’t have any os/arch specific calls, and this passes for amd64/ppc64le. I think this is result of the clock for qemu.  The clock doesn't seem to have `ms` precision.

Net: I think the right move is to remove it.

**Comment by gauravpbankar** [comment]
Hi Team, 

We are closing this issue,  As we have already commented on the same below is the reference.
https://github.com/ComplianceAsCode/compliance-operator/issues/79#issuecomment-1290727572
